import {
  BarChart3,
  BookOpenText,
  Boxes,
  ClipboardList,
  Gift,
  Grid3X3,
  LayoutDashboard,
  Settings,
  ShoppingCart,
  Store,
  Users,
  UtensilsCrossed,
} from 'lucide-react';
import type { SidebarMenuItem } from '../types/sidebar-menu-item.type';

export const MENU_ITEMS: SidebarMenuItem[] = [
  {
    id: 'dashboard',
    label: 'Tổng quan',
    icon: LayoutDashboard,
    href: '/',
    description: 'Tổng quan tình hình kinh doanh của cửa hàng',
    permission: 'dashboard',
  },
  {
    id: 'orders',
    label: 'Đơn hàng',
    icon: ClipboardList,
    href: '/orders',
    description: 'Theo dõi, xử lý và cập nhật trạng thái đơn hàng',
    permission: 'orders',
  },
  {
    id: 'products',
    label: 'Menu sản phẩm',
    icon: UtensilsCrossed,
    href: '/products',
    description: 'Menu cafe, giá bán và vòng đời sản phẩm',
    permission: 'products',
  },
  {
    id: 'formulas',
    label: 'Công thức / BOM',
    icon: BookOpenText,
    href: '/formulas',
    description: 'Công thức, giá vốn thành phần và định mức mẻ',
    permission: 'products',
  },
  {
    id: 'inventory',
    label: 'Nguyên liệu & Tồn kho',
    icon: Boxes,
    href: '/inventory',
    description: 'Kiểm soát kho, nguyên vật liệu và vị trí kho hàng',
    permission: 'products',
  },
  {
    id: 'purchases',
    label: 'Đơn nhập hàng',
    icon: ShoppingCart,
    href: '/purchases',
    description: 'Quản lý mua hàng, nhập kho và nhà cung cấp',
    permission: 'products',
  },
  {
    id: 'branches',
    label: 'Chi nhánh',
    icon: Store,
    href: '/branches',
    description: 'Quản lý mạng lưới kho và các điểm bán hàng',
    permission: 'reports',
  },
  {
    id: 'tables',
    label: 'Sơ đồ bàn',
    icon: Grid3X3,
    href: '/tables',
    description: 'Quản lý bàn, khu vực và trạng thái phục vụ theo thời gian thực',
    permission: 'reports',
  },
  {
    id: 'employees',
    label: 'Nhân viên',
    icon: Users,
    href: '/employees',
    description: 'Phân quyền, quản lý nhân viên, ca làm việc, chấm công',
    permission: 'employees',
  },
  {
    id: 'customers',
    label: 'Khách hàng',
    icon: Users,
    href: '/customers',
    description: 'Thông tin khách hàng, điểm tích lũy, lịch sử mua hàng',
    permission: 'orders',
  },
  {
    id: 'promotions',
    label: 'Khuyến mãi',
    icon: Gift,
    href: '/promotions',
    description: 'Quản lý chương trình khuyến mãi',
    permission: 'promotions',
  },
  {
    id: 'reports',
    label: 'Báo cáo',
    icon: BarChart3,
    href: '/reports',
    description: 'Xem các báo cáo về tình hình kinh doanh',
    permission: 'reports',
  },
  {
    id: 'settings',
    label: 'Cài đặt',
    icon: Settings,
    href: '/settings',
    description: 'Thay đổi các thiết lập trong ứng dụng',
    permission: 'settings',
  },
];
